export const SOURCE = "source"
export const TARGET = "target"
export const SELECT_ALL_DATA = "Select all data"
export const DESELECT_ALL_DATA = "Deselect all data"
export const INVERT_CURRENT_PAGE = "Invert current page"
export const REMOVE_ALL_DATA = "Remove all data"
export const BASIC = "Basic"
export const ONE_WAY = "One way"
export const SEARCH = "Search"
export const ADVANCED = "Advanced"
export const CUSTOM_DATASOURCE = "Custom datasource"
export const PAGINATION = "Pagination"
export const TABLE_TRANSFER = "Table transfer"
export const TREE_TRANSFER = "Tree transfer"
export const STATUS = "Status"

